title: this has yet to be defined
description: >
  that is, for you
baseurl: ""
url: "https://github.com/siawyoung/immaculate"
paginate:	2 # The number of posts to show per page on your homepage
name: "Jason Lo"
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
excerpt_separator: <!--more-->
kramdown:
  parse_block_html: true
gems:
  - jekyll-paginate
